{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base=ContentObjectAttribute}

{switch match=$attribute.content.info.type}
  {* string, integer, float *}
  {case in=array( 1, 4, 5 )}
    <input id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}"
           class="box ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}"
           type="text"
           size="50"
           name="{$attribute_base}_ymc_dynamic_ini_setting_{$attribute.id}[]"
           value="{$attribute.content.versioned_values['']|wash}" />
  {/case}
  
  {* Boolean: enabled/disabled. *}
  {case match=2}
    <select id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}"
            class="ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}"
            name="{$attribute_base}_ymc_dynamic_ini_setting_{$attribute.id}[]">
      <option value="enabled" {if $attribute.content.versioned_values['']|eq( 'enabled' )}selected="selected"{/if}>{'Enabled'|i18n( 'design/standard/class/datatype' )}</option>
      <option value="disabled" {if $attribute.content.versioned_values['']|eq( 'disabled' )}selected="selected"{/if}>{'Disabled'|i18n( 'design/standard/class/datatype' )}</option>
    </select>
  {/case}
  
  {* Boolean: true/false. *}
  {case match=3}
    <select id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}"
            class="ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}"
            name="{$attribute_base}_ymc_dynamic_ini_setting_{$attribute.id}[]">
      <option value="true" {if $attribute.content.versioned_values['']|eq( 'true' )}selected="selected"{/if}>{'True'|i18n( 'design/standard/class/datatype' )}</option>
      <option value="false" {if $attribute.content.versioned_values['']|eq( 'false' )}selected="selected"{/if}>{'False'|i18n( 'design/standard/class/datatype' )}</option>
    </select>
  {/case}
  
  {* Array. *}
  {case match=6}
    <div class="block">
      <label>{'Make empty array'|i18n( 'design/standard/class/datatype' )}:</label>
      <input id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}"
             class="ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}"
             type="checkbox"
             name="{$attribute_base}_ymc_dynamic_ini_setting_make_empty_array_{$attribute.id}" {$attribute.data_int|choose( '', 'checked=checked' )} />
    </div>
    
    <table class="list" cellspacing="0">
      <tr>
        <th class="tight">&nbsp;</th>
        <th>{'Key'|i18n( 'design/standard/content/datatype' )}</th>
        <th>{'Value'|i18n( 'design/standard/content/datatype' )}</th>
      </tr>
      {def $index_count=0}
      {foreach $attribute.content.versioned_values as $key => $value sequence array( bglight, bgdark ) as $sequence}
        <tr class="{$sequence}">
          {* Remove. *}
          <td>
            <input id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}_remove"
                   class="ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}"
                   type="checkbox"
                   name="{$attribute_base}_ymc_dynamic_ini_setting_remove_{$attribute.id}[]"
                   value="{$index_count}"
                   title="{'Select for removal.'|i18n( 'design/standard/content/datatype' )}" />
          </td>
          
          {* Key. *}
          <td>
            <input id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}"
                   class="box ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}"
                   type="text"
                   size="50"
                   name="{$attribute_base}_ymc_dynamic_ini_setting_key_{$attribute.id}[{$index_count}]"
                   value="{$key|wash}" />
          </td>
          
          {* Value. *}
          <td>
            <input id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}"
                   class="box ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}"
                   type="text"
                   size="50"
                   name="{$attribute_base}_ymc_dynamic_ini_setting_{$attribute.id}[{$index_count}]"
                   value="{$value|wash}" />
          </td>
        </tr>
        {set $index_count=$index_count|inc()}
      {/foreach}
      {undef $index_count}
    </table>
    
    <input id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}_ymc_dynamic_ini_setting_remove_selected"
           class="button ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}"
           type="submit"
           name="CustomActionButton[{$attribute.id}_ymc_dynamic_ini_setting_remove_selected]"
           value="{'Remove selected'|i18n('design/standard/content/datatype')}" />
    
    <input id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}_new_ymc_dynamic_ini_setting"
           class="button ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}"
           type="submit"
           name="CustomActionButton[{$attribute.id}_new_ymc_dynamic_ini_setting]"
           value="{'Add'|i18n('design/standard/content/datatype')}" />
  {/case}
{/switch}

{/default}
